export const TEST_ACTION = '[App] TEST_ACTION';

export const START_SOCKET_CONNECTION = '[App] START_SOCKET_CONNECTION';
export const START_SOCKET_CONNECTION_SUCCESS = '[App] START_SOCKET_CONNECTION_SUCCESS';
export const START_SOCKET_CONNECTION_FAIL = '[App] START_SOCKET_CONNECTION_FAIL';
